AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

LANG = {"zh": {'language': {'title':'语言',
                            'list1': '中文',
                            'list2': '英语',
                            },
               "index": {"suffix_albums": '的专辑库',
                         'view_details': '详情',

                         },
               'base': {'title': '唱片库',
                        'home': '主页',
                        'albums': '专辑库',
                        'songs': '曲目库',
                        'search': '搜索',
                        'add_album': '添加专辑',
                        'logout': '登出',
                        },
               'base_vistor': {'title': '欢迎来到唱片库',
                               'home': '主页',
                               'register': '注册',
                               'login': '登录',
                               },
               'songs': {'title': '所有曲目',
                         'view_all': '所有曲目',
                         'favorites': '喜欢的曲目',
                         'song_title': '曲目名',
                         'artist': '艺术家',
                         'audio_file': '文件',
                         'album': '专辑',
                         'favorite': '喜欢',
                         },
               'create_song': {'title': '添加新曲目',
                               'no_image': '没有专辑封面',
                               'view_all': '所有曲目',
                               'add_song': '添加',
                               'add_new_song': '添加新曲目',
                               'submit': '上传',
                               },
               'detail': {'no_image': '没有专辑封面',
                          'view_all': '所有曲目',
                          'add_song': '添加',
                          'all_songs': '添加新曲目',
                          'song_title': '曲目名',
                          'audio_file': '文件',
                          'favorite': '喜欢',
                          'actions': '动作',
                          'delete': '删除',
                          },
               },
        "en": {'language': {'title':'Language',
                            'list1': 'Chinese',
                            'list2': 'Englist',
                            },
               "index": {"suffix_albums": '\'s Albums',
                         'view_details': 'Details',

                         },
               'base': {'title': 'Albums',
                        'home': 'Home',
                        'albums': 'Albums',
                        'songs': 'Songs',
                        'search': 'Search',
                        'add_album': 'Add Album',
                        'logout': 'Logout',
                        },
               'base_vistor': {'title': 'Welcome To Albums',
                               'home': 'Home',
                               'register': 'Register',
                               'login': 'Login',
                               },
               'songs': {'title': 'All Songs',
                         'view_all': 'All Songs',
                         'favorites': 'Favorites',
                         'song_title': 'Song Title',
                         'artist': 'Artist',
                         'audio_file': 'File',
                         'album': 'Album',
                         'favorite': 'Favorite',
                         },
               'create_song': {'title': 'Add New Songs',
                               'no_image': 'No Album Cover',
                               'view_all': 'All Songs',
                               'add_song': 'Add',
                               'add_new_song': 'Add New Song',
                               'submit': 'Upload',
                               },
               'detail': {'no_image': 'No Album Cover',
                          'view_all': 'All Songs',
                          'add_song': 'Add',
                          'all_songs': 'Add New Song',
                          'song_title': 'Song Title',
                          'audio_file': 'File',
                          'favorite': 'Favorite',
                          'actions': 'Actions',
                          'delete': 'Delete',
                          },
               }
        }
